# Generated by Django 2.0.5 on 2018-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180606_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnsextrafield',
            name='discount_price',
            field=models.IntegerField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cnsextrafield',
            name='original_price',
            field=models.IntegerField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cnsextrafield',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
