# Generated by Django 2.0.5 on 2018-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180606_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cns',
            name='promote_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cnsextrafield',
            name='discount_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cnsextrafield',
            name='original_price',
            field=models.IntegerField(default=1),
        ),
    ]
